### ISSUE TITLE
Set the value of 'true_eval' when searching

### ISSUE THREAD

**Issue by f4nku4n** [EMI-Group/evoxbench#12]
Hi guys,
During the search, we have to use the performance on the validation set. So, do set 'true_eval' to False when we execute the algorithm?

In the tutorial, I see that you set the 'true_eval' to 'True' in the '_evaluate' function (e.g., line 36 - benchmark_citysegmop.py). If I was right, I think that we should set it to 'False' and I think that you should update all 3 tutorials to make sure that nobody makes that mistake.

**Comment by Zhenyu2Liang** [comment]
Hi,
If you want to use the performance on the validation set,  you need to set 'true_eval' to True.  'true_eval' set to True calculates the average of multiple runs.

If you have any further questions or concerns, feel free to ask. We're here to help!

**Comment by f4nku4n** [comment]
Hi,
Thanks for your response but I'm still confused. 
I thought that setting 'true_eval = True' would compute the performance on the testing set (e.g., lines 109-111 in [nb201.py](https://github.com/EMI-Group/evoxbench/blob/main/evoxbench/benchmarks/nb201.py)).

**Comment by Zhenyu2Liang** [comment]
Hello,
I'm sorry. I might have been a little wrong with my explanation.

You're right. During the search, 'true_eval' should be set to False (evaluate on the validation set). After the search, the result will be evaluated on the test set ('true_eval' = True) to get the final result.
I will update the tutorial code of Python. 

Thank you for your support and understanding.
