### ISSUE TITLE
Problem duplication in the CitySeg test suite

### ISSUE THREAD

**Issue by f4nku4n** [EMI-Group/evoxbench#13]
Hello guys,
I found that CitySeg/MOP5 and CitySeg/MOP10 have the same target objectives. I think there was a mistake in the objectives of CitySeg/MOP10. Can you check that?
I think the correct objectives are ``err&h2_latency&h2_energy_consumption&flops&params`` instead of ``err&h1_latency&h1_energy_consumption&flops&params``.

**Comment by AlpAcA0072** [comment]
Thank you for bringing up the issue! The bug will be fixed later.
