### ISSUE TITLE
Ask for Supplementary Materials

### ISSUE THREAD

**Issue by f4nku4n** [EMI-Group/evoxbench#4]
Hi, I'm reading your paper and I want to reproduce experiments in it. Unfortunately, I can't find out the Supplementary file to set the hyperparameter values for optimizers. Would you mind providing me with the Supplementary file?
Btw, does the hyperparameter 'true_eval' of benchmarks be set as 'False' when searching in your experiments, and we only turn it to 'True' at the evaluation phase (i.e., after the search is finished), isn't it?

**Comment by Zhenyu2Liang** [comment]
Hi, we will upload the supplementary file to **arXiv** tomorrow and inform you after uploading.
Yes, in the algorithm search process 'true_eval' is 'False'. The 'true_eval' set to 'True' after the search, to calculate more accurate objective function value.

**Comment by Zhenyu2Liang** [comment]
Hi, you can find the supplementary file on [**arXiv**](https://arxiv.org/abs/2208.04321) now.

**Comment by f4nku4n** [comment]
I saw it, thanks guys.
