### ISSUE TITLE
wrong objectives at IN-1K/MOP5 and IN-1K/MOP6

### ISSUE THREAD

**Issue by f4nku4n** [EMI-Group/evoxbench#5]
Hi there, could you check the objectives of IN-1K/MOP5 and IN-1K/MOP6 test suites, I found that they are duplicated in the IN-1K/MOP4 one.

**Comment by Zhenyu2Liang** [comment]
This is a bug. Now that it has been fixed, you can take a look at the revised code.
Thanks for reminding.
