### ISSUE TITLE
Issue running NSGA-III in pymoo for C-10/MOP test suite

### ISSUE THREAD

**Issue by thompsondd** [EMI-Group/evoxbench#7]
Hi, I am running the file benchmark_c10mop.py but I get the error:

![Screenshot 2023-04-25 144930](https://user-images.githubusercontent.com/42927678/234210349-66864ce9-cc0b-41c1-9e11-00ff71fb5adf.png)

I am using pymoo==0.6.0 and the lastest version evoxbench==1.0.3. Is there anyone help me to fix it?

**Comment by Zhenyu2Liang** [comment]
Hi, you can try to set it according to the following code on line 154.
`res = minimize(problem, algorithm, ('n_gen', n_gen), verbose=False)`

**Comment by thompsondd** [comment]
> Hi, you can try to set it according to the following code on line 154. `res = minimize(problem, algorithm, ('n_gen', n_gen), verbose=False)`

It works. Thank you.
